Repository WEBsinjyuku/meister-hackers, pull requests merged in 2019-02, with the labels that each got.

#95 PRテンプレートの修正
  Gemfile
  Gemfile.lock
  PULL_REQUEST_TEMPLATE.md
  config/environments/development.rb
Labels: LGTM-dh-megane, LGTM-takahashi19

#100 project テーブル削除 + post に repository 追加
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/models/project.rb
  db/migrate/20190204121628_delete_projects.rb
  db/migrate/20190204123016_add_repository_to_posts.rb
  db/schema.rb
  spec/controllers/posts_controller_spec.rb
  spec/factories/posts.rb
  spec/factories/projects.rb
  spec/models/post_spec.rb
  spec/models/project_spec.rb
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#77 新規投稿，編集機能 とりあえずmasterへ
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/models/user.rb
  app/views/posts/_form.html.slim
  app/views/posts/edit.html.slim
  app/views/posts/new.html.slim
  config/routes.rb
  db/migrate/20190127045138_add_columns_to_posts.rb
  db/migrate/20190127105228_create_projects.rb
  db/migrate/20190204121628_delete_projects.rb
  db/migrate/20190204123016_add_repository_to_posts.rb
  db/schema.rb
  spec/controllers/posts_controller_spec.rb
  spec/factories/posts.rb
  spec/factories/users.rb
  spec/models/post_spec.rb
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#105 プロジェクト一覧画面−画面遷移
  app/controllers/posts_controller.rb
  app/views/posts/index.html.slim
  config/routes.rb
Labels: LGTM-takaaa200, LGTM-tsu-nera, レビューして

#108 GitHub API Client
  Gemfile
  Gemfile.lock
  config/application.rb
  config/initializers/octokit.rb
  lib/github_oss/github_fetcher.rb
Labels: LGTM-dh-megane, LGTM-takahashi19, レビューして

#106 プロジェクト一覧画面-固定HTMLでの画面イメージ作成
  app/views/posts/index.html.slim
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#121 Bulmaバージョンアップ 0.7.4
  app/views/layouts/application.html.slim
Labels: LGTM-LeonardoMatusaki, LGTM-tsu-nera, レビューして

#126 wip（固定HTMLをVue文法で置換え）
  Gemfile.lock
Labels: WIP

#140 ESLint導入
  .eslintignore
  .eslintrc.js
  app/javascript/app.vue
  app/javascript/packs/application.js
  app/javascript/packs/hello_vue.js
  package.json
  sideci.yml
  yarn.lock
Labels: LGTM-dh-megane, LGTM-hiromoto-kazuya, LGTM-takahashi19, レビューして

#144 プロジェクト詳細画面-固定HTMLでの画面イメージ作成
  app/assets/stylesheets/postsshow.css
  app/controllers/posts_controller.rb
  app/views/layouts/application.html.slim
  app/views/posts/show.html.slim
  config/routes.rb
  db/schema.rb
Labels: LGTM-tsu-nera, レビューして

#146 掲示板コメント機能
  .eslintrc.js
  Gemfile
  Gemfile.lock
  Procfile
  app/controllers/messages_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/sessions_controller.rb
  app/javascript/components/atoms/.keep
  app/javascript/components/molecules/.keep
  app/javascript/components/organisms/.keep
  app/javascript/components/organisms/MessageBoard.vue
  app/javascript/packs/posts/show.vue.js
  app/models/message.rb
  app/models/post.rb
  app/models/user.rb
  app/views/posts/show.html.slim
  config/routes.rb
  db/migrate/20190219132512_create_messages.rb
  db/schema.rb
  docker-compose.yml
  package.json
  spec/factories/messages.rb
  spec/factories/posts.rb
  spec/factories/users.rb
  spec/models/message_spec.rb
  spec/models/post_spec.rb
  yarn.lock
Labels: LGTM-dh-megane, LGTM-takahashi19

#160 マイページ(edit)
  app/controllers/profiles_controller.rb
  app/javascript/components/molecules/UserPost.vue
  app/javascript/components/molecules/UserProfile.vue
  app/javascript/components/organisms/MyPage.vue
  app/javascript/components/organisms/MyPageForm.vue
  app/javascript/packs/users/edit.vue.js
  app/views/users/edit.html.slim
  config/routes.rb
  package.json
  spec/factories/profiles.rb
Labels: レビューして

#161 Rollbarの導入
  Gemfile
  Gemfile.lock
  config/initializers/rollbar.rb
Labels: LGTM-takahashi19, レビューして

#135 WIP【新規投稿機能・編集機能】
  Gemfile
  Gemfile.lock
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/views/posts/_form.html.slim
  db/migrate/20190222031603_add_column_to_post.rb
  db/schema.rb
  spec/factories/posts.rb
  spec/models/post_spec.rb
Labels: LGTM-dh-megane, LGTM-tsu-nera, WIP, レビューして

#166 プロジェクト名変更対応
  config/cable.yml
  config/database.yml
  config/environments/production.rb
  package.json
Labels: LGTM-dh-megane, レビューして

#147 マイページ機能(show, edit)
  .eslintrc.js
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/controllers/profiles_controller.rb
  app/controllers/users_controller.rb
  app/javascript/components/molecules/UserPost.vue
  app/javascript/components/molecules/UserProfile.vue
  app/javascript/components/organisms/MyPage.vue
  app/javascript/components/organisms/MyPageForm.vue
  app/javascript/packs/users/edit.vue.js
  app/javascript/packs/users/show.vue.js
  app/models/profile.rb
  app/models/user.rb
  app/views/layouts/_navbar.html.slim
  app/views/layouts/application.html.slim
  app/views/users/edit.html.slim
  app/views/users/show.html.slim
  config/routes.rb
  db/migrate/20190221051923_create_profiles.rb
  db/schema.rb
  lib/tasks/db.rake
  lib/tasks/test_datas.rake
  package.json
  spec/controllers/users_controller_spec.rb
  spec/factories/profiles.rb
  spec/factories/users.rb
  spec/models/profile_spec.rb
Labels: LGTM-hiromoto-kazuya, LGTM-takahashi19, レビューして

#162 RSpec修復
  spec/controllers/posts_controller_spec.rb
  spec/rails_helper.rb
Labels: LGTM-hiromoto-kazuya, LGTM-takahashi19, レビューして

#179 auth情報からgithubアカウント画像を取得、userに保存
  app/controllers/sessions_controller.rb
  app/models/user.rb
  db/migrate/20190224073550_add_column_to_users.rb
  db/schema.rb
Labels: LGTM-LeonardoMatusaki, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#180 navbarのレイアウト調整
  app/assets/stylesheets/application.css
  app/views/layouts/_navbar.html.slim
Labels: LGTM-dh-megane, LGTM-hiromoto-kazuya, LGTM-tsu-nera, レビューして

#136 JSON取得方法をAPIに切り替え
  app/controllers/posts_controller.rb
  app/javascript/packs/posts/index.vue.js
  app/models/post.rb
  app/models/user.rb
  app/views/posts/index.html.slim
  lib/github_oss/github_fetcher.rb
Labels: LGTM-hiromoto-kazuya, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#181 footerの作成
  app/assets/stylesheets/application.css
  app/views/layouts/_footer.html.slim
  app/views/layouts/application.html.slim
  public/connpass.png
Labels: LGTM-dh-megane, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#185 マイページ不具合修正
  app/controllers/profiles_controller.rb
  app/javascript/components/molecules/UserProfile.vue
  app/javascript/components/organisms/MyPage.vue
  app/javascript/components/organisms/MyPageForm.vue
Labels: LGTM-LeonardoMatusaki, LGTM-dh-megane, レビューして

#197 current_userユーザと画像アイコンクリック時usershowに変遷追加
  app/assets/stylesheets/application.css
  app/controllers/users_controller.rb
  app/views/layouts/_navbar.html.slim
  public/githubicon.png
  public/logo1.gif
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#104 プロジェクト一覧機能
  app/controllers/posts_controller.rb
  app/javascript/packs/posts/index.vue.js
  app/models/user.rb
  app/views/posts/index.html.slim
Labels: LGTM-tsu-nera, レビューして

#218 Post create バク修正
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/models/user.rb
  db/migrate/20190227220130_add_nickname_to_users.rb
  db/migrate/20190227222145_add_owner_to_posts.rb
  db/schema.rb
  spec/factories/posts.rb
  spec/factories/users.rb
  spec/models/post_spec.rb
Labels: LGTM-dh-megane, LGTM-hiromoto-kazuya, LGTM-takahashi19

#215 個別投稿(show)
  app/assets/stylesheets/application.css
  app/assets/stylesheets/postsshow.css
  app/controllers/posts_controller.rb
  app/javascript/components/organisms/MessageBoard.vue
  app/models/post.rb
  app/views/layouts/application.html.slim
  app/views/posts/show.html.slim
  spec/factories/users.rb
Labels: LGTM-tsu-nera, レビューして

#221 テストデータ作成タスク不具合修正
  lib/tasks/test_datas.rake
  spec/factories/posts.rb
  spec/factories/users.rb
Labels: LGTM-tsu-nera

#230 header修正
  app/assets/stylesheets/application.css
Labels: LGTM-tsu-nera, レビューして

#231 vueコンポーネントを表示できるように修正(Turbolink廃止)
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/models/post.rb
  app/models/user.rb
  app/views/layouts/application.html.slim
  app/views/posts/show.html.slim
  spec/factories/posts.rb
  spec/factories/users.rb
  spec/models/post_spec.rb
Labels: レビューして

#220 footer修正
  app/assets/stylesheets/application.css
  app/views/layouts/_footer.html.slim
  app/views/layouts/application.html.slim
  app/views/posts/index.html.slim
Labels: レビューして

#232 エラー発生時の遷移処理
  app/controllers/application_controller.rb
  app/controllers/posts_controller.rb
  app/views/errors/error_404.html.slim
  app/views/errors/error_500.html.slim
  app/views/layouts/application.html.slim
  app/views/posts/index.html.slim
  config/routes.rb
Labels: LGTM-tsu-nera, レビューして

#239 routingにenv.production?追加
  config/routes.rb
Labels: LGTM-tsu-nera

#240 headerとコンテンツのwidthとpadding修正
  app/assets/stylesheets/application.css
Labels: LGTM-hiromoto-kazuya, LGTM-takahashi19, レビューして

#242 #227修正
  app/controllers/profiles_controller.rb
  app/javascript/components/organisms/MyPage.vue
  app/views/posts/show.html.slim
  config/routes.rb
Labels: LGTM-tsu-nera, レビューして

#243 devise日本語化&flash表示
  app/assets/stylesheets/application.css
  app/views/layouts/application.html.slim
  config/locales/devise.ja.yml
Labels: レビューして

#234 Vue.jsにおけるログイン状態の管理
  app/controllers/profiles_controller.rb
  app/javascript/components/molecules/UserProfile.vue
  app/javascript/components/organisms/MyPage.vue
Labels: LGTM-hiromoto-kazuya, レビューして

#249 Index fix#225
  app/views/posts/index.html.slim
Labels: LGTM-takahashi19, LGTM-tsu-nera, high priority

#255 content 改行有効
  app/views/posts/show.html.slim
Labels: LGTM-hiromoto-kazuya, LGTM-tsu-nera, high priority, レビューして

#253 プロジェクト投稿 Updateすると落ちる
  app/models/post.rb
Labels: LGTM-hiromoto-kazuya, LGTM-tsu-nera, high priority, レビューして
