Repository WEBsinjyuku/meister-hackers, pull requests merged in 2019-03, with the labels that each got.

#252 新規投稿部分修正#42
  app/assets/stylesheets/postsshow.css
  app/views/posts/_form.html.slim
Labels: LGTM-dh-megane, LGTM-hiromoto-kazuya, LGTM-tsu-nera, レビューして

#247 post投稿/編集フォームの不具合修正
  app/views/posts/_form.html.slim
  config/locales/model.ja.yml
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#260 募集終了機能の追加 index
  app/controllers/posts_controller.rb
  app/helpers/application_helper.rb
  app/views/posts/index.html.slim
Labels: LGTM-hiromoto-kazuya, レビューして

#262 posts#showページにリポジトリURLを追加
  app/assets/stylesheets/postsshow.css
  app/views/posts/show.html.slim
Labels: LGTM-shikky0331, LGTM-takahashi19, レビューして

#269 募集中・募集停止 日付更新 new・edit
  app/models/post.rb
  db/migrate/20190303081258_add_column_to_posts.rb
  db/schema.rb
Labels: LGTM-hiromoto-kazuya, LGTM-tsu-nera, レビューして

#259 削除・募集終了機能
  app/controllers/posts_controller.rb
  app/helpers/application_helper.rb
  app/models/post.rb
  app/views/posts/index.html.slim
  app/views/posts/show.html.slim
  config/routes.rb
  db/migrate/20190303081258_add_column_to_posts.rb
  db/schema.rb
Labels: LGTM-hiromoto-kazuya, LGTM-shikky0331, LGTM-tsu-nera, レビューして

#290 両脇の余白作ったよ
  app/assets/stylesheets/application.css
Labels: レビューして

#288 profile_controller updateの不具合修正とflash追加
  app/controllers/profiles_controller.rb
  app/javascript/components/organisms/MyPageForm.vue
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#287 デザイン適用 index
  app/controllers/posts_controller.rb
  app/views/posts/index.html.slim
Labels: LGTM-hiromoto-kazuya, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#266 wip リポジトリ名チェック処理
  app/models/concerns/post_validator.rb
  app/models/post.rb
  app/views/posts/_form.html.slim
  lib/github_oss/github_fetcher.rb
Labels: LGTM-dh-megane, LGTM-hiromoto-kazuya, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#297 error_404 add
  app/assets/stylesheets/application.css
  app/views/errors/error_404.html.slim
Labels: LGTM-takahashi19, レビューして

#296 footerデザイン再適用
  app/assets/stylesheets/application.css
  app/views/layouts/_footer.html.slim
Labels: LGTM-dh-megane, レビューして

#295 プロジェクト詳細ページのデザイン修正
  app/assets/stylesheets/application.css
  app/assets/stylesheets/postsshow.css
  app/views/posts/show.html.slim
Labels: LGTM-dh-megane, LGTM-hiromoto-kazuya, レビューして

#302 リポジトリ存在チェック等 投稿画面考慮漏れ対応
  app/assets/stylesheets/application.css
  app/models/post.rb
  app/views/posts/_form.html.slim
Labels: LGTM-takahashi19, レビューして

#291 参加ボタン押下時の連絡先表示機能
  Gemfile
  app/controllers/posts_controller.rb
  app/javascript/packs/posts/show.vue.js
  app/models/concerns/post_validator.rb
  app/views/posts/_form.html.slim
  app/views/posts/show.html.slim
  db/migrate/20190308053730_add_slack_url_column_to_posts.rb
  db/schema.rb
Labels: LGTM-dh-megane, LGTM-takahashi19, レビューして

#314 MessageBoardのデザイン修正
  app/assets/stylesheets/postsshow.css
  app/javascript/components/organisms/MessageBoard.vue
Labels: LGTM-dh-megane, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#318 modalバグ修正
  app/views/posts/show.html.slim
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#320 posts#indexの並び順変更
  app/controllers/posts_controller.rb
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#319 Bugs#posts/show edit#306
  app/assets/stylesheets/postsshow.css
  app/controllers/profiles_controller.rb
  app/javascript/components/organisms/MyPageForm.vue
  app/views/posts/show.html.slim
Labels: レビューして

#321 非ログイン時も募集停止見えるように修正
  app/views/posts/show.html.slim
Labels: LGTM-dh-megane, レビューして

#304 デザイン再適応[Show Post View with Button (show.html.slim, _form.html.slim)]
  app/assets/stylesheets/posts_form.css
  app/views/posts/_form.html.slim
Labels: LGTM-LeonardoMatusaki, レビューして

#313 Bugfix#244 user edit画面の権限まわり
  app/controllers/profiles_controller.rb
  app/javascript/components/molecules/UserProfile.vue
  app/javascript/components/organisms/MyPage.vue
  app/javascript/components/organisms/MyPageForm.vue
  app/models/post.rb
  config/routes.rb
  spec/factories/posts.rb
  spec/models/post_spec.rb
Labels: LGTM-takahashi19, レビューして

#322 掲示板コメント 空白投稿をガード
  app/javascript/components/organisms/MessageBoard.vue
Labels: レビューして

#325 起案者のSlackワークスペースへの参加方法とチャンネル作成手順
  app/views/posts/_form.html.slim
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#326 README追記
  README.md
Labels: WIP

#336 存在しないpostsのURLを叩くとエラーになる
  app/controllers/posts_controller.rb
  app/javascript/components/organisms/MyPage.vue
Labels: LGTM-dh-megane, レビューして

#339 404jpg add
  public/404.jpg
Labels: レビューして

#298 mypageformのデザイン再適用
  app/javascript/components/organisms/MyPageForm.vue
  config/webpack/development.js
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#323 【@takahashi19判断待】4部分デザイン修正
  app/assets/stylesheets/application.css
  app/assets/stylesheets/postsshow.css
  app/views/layouts/_footer.html.slim
  app/views/layouts/_navbar.html.slim
  app/views/posts/_form.html.slim
  app/views/posts/edit.html.slim
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#345 GitHub草
  app/controllers/profiles_controller.rb
  app/javascript/components/organisms/MyPage.vue
  package.json
  yarn.lock
Labels: LGTM-dh-megane, レビューして

#347 Prioduction環境でのVueコンポーネント CSS読込設定
  config/webpack/production.js
Labels: LGTM-tsu-nera, レビューして

#293 デザイン適用 MyPage
  app/javascript/components/molecules/UserPost.vue
  app/javascript/components/molecules/UserProfile.vue
  app/javascript/components/organisms/MyPage.vue
  app/views/users/show.html.slim
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#360 posts/index 7件以上の投稿時の画面レイアウト崩れ対応
  app/views/posts/index.html.slim
Labels: LGTM-tsu-nera, レビューして

#348 MyPageFormの入力値検証
  app/controllers/profiles_controller.rb
  app/javascript/components/organisms/MyPageForm.vue
  app/models/profile.rb
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#364 posts/show height値が大きい場合に画面下部が白くなる
  app/assets/stylesheets/application.css
  app/views/posts/index.html.slim
Labels: LGTM-takahashi19, レビューして

#350 sns share button作成
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/javascript/components/molecules/UserProfile.vue
  app/views/layouts/application.html.slim
  app/views/posts/edit.html.slim
  app/views/posts/index.html.slim
  app/views/posts/new.html.slim
  app/views/posts/show.html.slim
  app/views/users/edit.html.slim
  app/views/users/show.html.slim
Labels: LGTM-dh-megane, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#365 MeaagesBoard 機能改善
  app/controllers/messages_controller.rb
  app/javascript/components/organisms/MessageBoard.vue
  app/models/message.rb
  app/views/posts/show.html.slim
  config/routes.rb
  db/migrate/20190316230307_add_column_to_messages.rb
  db/schema.rb
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#369 リンク調整
  app/views/layouts/_footer.html.slim
Labels: LGTM-dh-megane, LGTM-takahashi19, レビューして

#378 Slackチャンネル名表示
  app/views/posts/show.html.slim
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#377 posts/index 表示順見直し
  app/controllers/posts_controller.rb
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#387 twiiter-cardのimage を設定
  app/helpers/application_helper.rb
  public/Meister Hackers two-rows.png
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#388 ユーザー編集の自己紹介覧修正と文字数制限変更
  app/javascript/components/molecules/UserProfile.vue
  app/javascript/components/organisms/MyPageForm.vue
  app/models/profile.rb
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#386 LP画面（レスポンシブ対応済み）
  app/assets/images/bg.jpeg
  app/assets/stylesheets/application.css
  app/assets/stylesheets/top.css
  app/controllers/home_controller.rb
  app/views/errors/error_404.html.slim
  app/views/errors/error_500.html.slim
  app/views/home/top.html.slim
  app/views/layouts/application.html.slim
  app/views/posts/_form.html.slim
  app/views/posts/index.html.slim
  app/views/posts/show.html.slim
  app/views/users/edit.html.slim
  app/views/users/show.html.slim
  config/routes.rb
  spec/controllers/home_controller_spec.rb
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして
