Repository WEBsinjyuku/meister-hackers, pull requests merged in 2019-04, with the labels that each got.

#389 twitter-card-image　再設定
  app/helpers/application_helper.rb
Labels: レビューして

#400 LPページ完成
  app/assets/images/bg.jpeg
  app/assets/stylesheets/top.css
  app/views/home/top.html.slim
Labels: LGTM-takahashi19, LGTM-tsu-nera, レビューして

#406 未ログイン時のユーザ情報閲覧
  app/views/users/show.html.slim
Labels: LGTM-tsu-nera, レビューして
