Repository WEBsinjyuku/meister-hackers, pull requests merged in 2019-01, with the labels that each got.

#40 Rails開発環境導入 with Docker
  Dockerfile
  config/database.yml
  docker-compose.yml
Labels: LGTM-shikky0331, LGTM-takahashi19

#36 login for dev
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/sessions/test.html.erb
  config/routes.rb
  db/migrate/20190116131702_create_users.rb
  db/schema.rb
  db/seeds.rb
Labels: LGTM-takahashi19, LGTM-tsu-nera

#41 ロボコップ導入
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/sessions_helper.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/user.rb
  config.ru
  package.json
  sideci.yml
Labels: LGTM-shikky0331, LGTM-takahashi19

#51 Feature/slim#47
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.slim
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.html.slim
  app/views/layouts/mailer.text.erb
  app/views/layouts/mailer.text.slim
  app/views/sessions/test.html.erb
  app/views/sessions/test.html.slim
Labels: LGTM-dh-megane, LGTM-takahashi19

#58 レビューのルール改訂
  CONTRIBUTING.md
Labels: LGTM-dh-megane, LGTM-takahashi19

#63 Feature/rspec#52
  .rspec
  Gemfile
  Gemfile.lock
  config/application.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: レビューして

#67 refs #66 create posts table
  app/models/post.rb
  db/migrate/20190123083731_create_posts.rb
  db/schema.rb
Labels: LGTM-takahashi19, LGTM-tsu-nera

#69 Heroku設定
  config/routes.rb
Labels: LGTM-takahashi19, たすけて

#79 Feature/add columns to post#42
  app/models/post.rb
  app/models/user.rb
  db/migrate/20190127045138_add_columns_to_posts.rb
  db/schema.rb
  spec/factories/posts.rb
  spec/factories/users.rb
  spec/models/post_spec.rb
Labels: LGTM-tsu-nera, レビューして

#82 Feature/controller routes#42
  app/controllers/posts_controller.rb
  app/views/posts/_form.html.slim
  app/views/posts/edit.html.slim
  app/views/posts/new.html.slim
  config/routes.rb
  spec/controllers/posts_controller_spec.rb
Labels: LGTM-dh-megane, LGTM-takahashi19, LGTM-tsu-nera, レビューして

#83 refs #create project table
  app/models/post.rb
  app/models/project.rb
  db/migrate/20190127105228_create_projects.rb
  db/schema.rb
  spec/factories/projects.rb
  spec/models/project_spec.rb
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして

#89 Featrue/add gem#88　bulmaのgemのみ導入
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/views/layouts/application.html.slim
Labels: LGTM-dh-megane, LGTM-tsu-nera, レビューして
